const Endpoints = {
  LOGIN: "auths/login",
  LOGOUT: "auths/logout",
  REGISTER: "auths/register",
  GOOGLE: "auths/google",
  FORGOT: "auths/forgotPassword",
  OTP: "auths/verify",
  RESET: "auths/resetPassword",
  ADMIN_PROFILE: "profile",
  CHANGE_PASSWORD: "changePassword",
  USER_LIST: "usersList",
  VIEW_PRODUCTS: "products",
  PRODUCT: "product",
  COLOR: "product/color",
  FEATURED_PRODUCTS_LIST: "featured_products",
  FEATURED_PRODUCT: "featured_product",
  NEWSLETTER: "newsletter_subscriptions",
  DELETE_NEWSLETTER: "newsletter_subscription",
  MAIL: "send_newsletter_email",
  CATEGORY_LIST: "product_categories",
  CATEGORY: "product_category",
  UPLOAD_IMAGES: "images/upload",
};

export default Endpoints;
